# Generated by Django 4.2.1 on 2023-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_apellidos_alter_usuario_edificio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='piso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
    ]
